name: Playwright API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install


    - name: Run Playwright tests
      run: npx playwright test --reporter=list,html

    - name: Upload Playwright HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report
